# Generated by Django 3.2.4 on 2021-06-14 18:14

from django.db import migrations, models
import limb.models
import limb.utils


class Migration(migrations.Migration):

    dependencies = [
        ('limb', '0003_alter_ppg_ppgdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppg',
            name='ppgdata',
            field=models.FileField(storage=limb.utils.OverwriteStorage(), upload_to=limb.models.get_user_path),
        ),
    ]
