# Generated by Django 3.2.4 on 2021-06-17 06:25

import LimbRescueWeb.models
import LimbRescueWeb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('ppgdata', models.FileField(storage=LimbRescueWeb.utils.OverwriteStorage(), upload_to=LimbRescueWeb.models.get_user_path)),
            ],
            options={
                'db_table': 'ppg',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=32)),
            ],
            options={
                'verbose_name': 'Username',
                'verbose_name_plural': 'Username',
            },
        ),
    ]
